sensevoice_stt_node:
  ros__parameters:
    model_dir: /home/lerobot/aicapstone/lerobot/capstone/gengen/models/sensevoice_ko
    model_name: model.onnx
    language: ko
    device: cpu

    sample_rate: 16000
    channels: 1
    frame_ms: 30
    silence_duration_ms: 800
    min_speech_ms: 200
    pre_roll_ms: 200
    energy_threshold: 0.01

    audio_device: 0
    use_channel_index: 0

    publish_topic: /stt/text
